### ISSUE TITLE
نبودن رخداد برای تغییر تاریخ

### ISSUE THREAD

**Issue by mahdihp** [VahidN/DNTPersianComponents.Blazor#1]
<div dir="rtl">

# توضيحات
وقتی از حالت @bind-Value 
استفاده میشه  متد و رخدادی برای تغییر تاریخ تدارد.
![image](https://user-images.githubusercontent.com/6378625/157400154-e95c1cee-2951-4853-acbd-41c844f10469.png)

## محيط اجرايى

```
.NET SDK version: 
DNTPersianComponents.Blazor version: 
```

## روش بازتوليد مشكل

```C#
كدهاى خود را در اين قسمت قرار دهيد
```

## خروجى مشكل دار

```
پيام استثناء و همچنين استك‌تريس كامل را در اينجا قرار دهيد
```

**Comment by VahidN** [comment]
<div dir="rtl">
 bind-Value دو طرفه است و به صورت خودكار ValueChanged جزئي از آن است و نيازي به پياده سازي اضافي ندارد

در كل در blazor نمي‌توانيد هم bind-Value را بنويسيد و هم ValueChanged را. البته مي‌توانيد Value و ValueChanged را داشته باشيد تا از حالت بايندينگ دوطرفه به يك طرفه برسيد ولي در كل نيازي به آن نيست.

**Comment by mahdihp** [comment]
تشکر اوکی شد
ولی اگر بخوام به این کامپوننت تاریخ بده و تابع StateHasChanged();  صدا میزنم تاریخ کامپوننت بروز نمیشه.

**Comment by Mahdihp** [comment]
یه مسله اگر مقدار بایند شده من Nullable باشه باید چیکار کرد
ایا @bind-Value نال پذیر هست؟
