### ISSUE TITLE
مشکل محاسبه یک روز کمتر

### ISSUE THREAD

**Issue by mahdihp** [VahidN/DNTPersianComponents.Blazor#2]
<div dir="rtl">

# توضيحات

موقع استفاده مشکل محاسبه یک روز کمتر را دارم
شبیه اون مشکلی که در انگولار بود که یک روز کمتر تاریخ رو میزد
با این که CultureInfo روی fa-IR 

## محيط اجرايى

```
.NET SDK version: 
DNTPersianComponents.Blazor version: 
```

## روش بازتوليد مشكل

```C#
كدهاى خود را در اين قسمت قرار دهيد
```

## خروجى مشكل دار

```
پيام استثناء و همچنين استك‌تريس كامل را در اينجا قرار دهيد
```

**Comment by VahidN** [comment]
توضيحات كافي نيست

**Comment by mahdihp** [comment]
تو این مقاله یکی از کاربران به مشکل محاسبه کمتر از یک روز بر خورده بود 
https://www.dntips.ir/post/2890/%d8%b4%d9%85%d8%b3%db%8c-%d8%b3%d8%a7%d8%b2%db%8c-date-picker-%d8%aa%d9%88%da%a9%d8%a7%d8%b1-angular-material-6x
 الان منم از این کامپوننت استفاده می کنم بعد از انتخاب تاریخ یک روز کمتر تاریخ را میزنه

**Comment by VahidN** [comment]
اين‌ها ربطي به هم ندارند. زير ساخت اين كامپوننت كلاس تقويم شمسي خود دات نت است، بدون هيچ تغييري. بررسي كنيد چه تاريخي را دريافت كرديد. برنامه را ديباگ كنيد. هرچيزي كه دريافت كرده، همان را نشان مي‌دهد.

**Comment by mahdihp** [comment]
بله جرف درسته
ولی من الان تاریخ را 1400/5/1 انتخاب می کنم وقتی اطلاعات ذخیره می کنم دوباره تاریخ ار نشون میدم و از دیتابیس می کشم بیرون تاریه یک روز کمتر میزنه و تاریه 1400/4/31 هست؟
دتتابیسم مونگو دی بی هست

**Comment by VahidN** [comment]
در مورد تاريخ در mongodb [اين نكات را بايد رعايت كنيد](http://binaryintellect.net/articles/6c715186-97b1-427a-9ccc-deb3ece7b839.aspx) و بيشتر مباحث سمت سرور هست تا اين كامپوننت سمت كلاينت.

يعني شما تاريخ ابتداي روز را به آن مي‌دهيد و mongodb آن‌را به صورت utc ذخيره مي‌كند كه مي‌شود روز قبل. اين تفاوت بخاطر نحوه‌ي ذخيره سازي utc آن بانك اطلاعاتي است.

**Comment by mahdihp** [comment]
ممنون مشکل با اون لینک آموزشی حل شد.
